vscode:
  extensions:
    - ms-python.python
    - shardulm94.trailing-spaces
ports:
  - port: 3002
    onOpen: ignore
    visibility: private
  - port: 3005
    onOpen: ignore
    visibility: private
tasks:
- command: >
    pip install -e . &&
    docker build . --tag phillmac/dagr_selenium