# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Test & build
  displayName: Test & build image
  jobs:
  - job: RunTests
    displayName: Run tests
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Bash@3
      inputs:
        filePath: 'scripts/run-dagr-revamped-tests.sh'

  - job: BuildImage
    displayName: Build image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        filePath: 'scripts/run-dagr-revamped-tests.sh'

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'phillmac/dagr_selenium'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(tag)

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'phillmac/dagr_selenium'
        command: 'push'
        tags: |
          latest
          $(tag)
