# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- feat/async

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: TestAndBuild
  displayName: Test & build image
  jobs:

    - job: BuildImage
      displayName: Build image
      pool:
        vmImage: ubuntu-latest
      steps:

      - task: Docker@2
        displayName: Build selenium image
        inputs:
          containerRegistry: 'Docker Hub'
          repository: 'phillmac/dagr_selenium'
          command: build
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          tags: |
            latest-async
            $(tag)

      - task: Docker@2
        displayName: Push selenium image
        inputs:
          containerRegistry: 'Docker Hub'
          repository: 'phillmac/dagr_selenium'
          command: 'push'
          tags: |
            latest-async
            $(tag)

      - task: Bash@3
        displayName: Build DAGR tests image
        inputs:
          targetType: 'inline'
          script: 'docker build . -t phillmac/dagr_revamped_tests -f scripts/dagr_revamped.dockerfile'

      - task: Bash@3
        displayName: Run HTTP IO tests
        inputs:
          filePath: 'scripts/run-dagr-revamped-tests.sh'
        env:
          TEST_IO_CLASS: http
          IMAGE_TAG: $(tag)

      - task: Bash@3
        displayName: Run default IO tests
        inputs:
          filePath: 'scripts/run-dagr-revamped-tests.sh'
        env:
          TEST_IO_CLASS: default
          IMAGE_TAG: $(tag)

